services:
  - type: web
    name: pdftovideo
    runtime: python
    plan: free
    region: oregon # Choose your preferred region
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    autoDeploy: true
    repo: https://github.com/mosesnkoromo/PdfToVideoConverter
    branch: main
